# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Get all Secrets found by GHAS in an org

on:
  workflow_dispatch:
    inputs:
      org-name:
        description: 'Name of the org'
        required: true
        default: octokit

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ORG_NAME: octodemo
      PAT: ${{ secrets.SECRETS_PAT }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: 15
    - run: npm install
    - run: node index.js --token $PAT --org $ORG_NAME
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      if: failure()
      with:
        name: secrets.json
        path: secrets.json
